import equals_test from './equals_test'
import add_test from './add_test'
import subtract_test from './subtract_test'
import multiply_test from './multiply_test'
import divide_test from './divide_test'
import prop_test from './prop_test'
import inc_test from './inc_test'
